version: '3.4'

services: 

    traefik:
        command: --api --docker --docker.exposedbydefault=false

    web:
       build:  
        target: dev-stage
       command: 
        npm run serve 
       labels: 
        - traefik.port=8000 
        - traefik.frontend.rule=Host:vuefinances.${DOMAIN}
       volumes: 
        - ./dependencias/front:/usr/app  
        - /usr/app/node_modules

    api:
       command: 
        npm run dev
       labels: 
        - traefik.frontend.rule=Host:api.vuefinances.${DOMAIN} 
       volumes: 
        - ./dependencias/back:/usr/app  
        - /usr/app/node_modules
           